services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: boostshortener
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: ["npm", "run", "start"] 

volumes:
  db_data: